export const API_BASE_URL = 'http://localhost:3001/api'
export const GENERIC_PICTURE_PATH = '/assets/general/genericUser.png'
export const WHATSAPP_URL_BASE = 'https://wa.me/+972'
export const ADIR_LINKEDIN_URL = 'https://www.linkedin.com/in/adir-barak-4ab698257/'
export const ARIE_LINKEDIN_URL = 'https://www.linkedin.com/in/arie-levental/'
